# Generated by Django 4.1.2 on 2023-04-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000020FA0A7DC00>')),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, max_length=1000, null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
    ]
