# Generated by Django 4.1.2 on 2023-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x000001AF3E87DBD0>'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='propertys',
            field=models.ManyToManyField(blank=True, null=True, related_name='propertys', to='property.property'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='property_watch', to='property.property'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
