# Generated by Django 4.1.2 on 2023-04-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_imaga1_alter_property_imaga2_and_more'),
        ('account', '0003_alter_profile_created_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='realstate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x00000256706CDC00>'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='propertys',
            field=models.ManyToManyField(related_name='propertys', to='property.property'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(related_name='property_watch', to='property.property'),
        ),
    ]
