# Generated by Django 4.1.2 on 2023-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/account/%Y/%m/%d/'),
        ),
    ]
