# Generated by Django 4.1.2 on 2023-04-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('vpm', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('imaga1', models.ImageField(default='defaults/default.jpg', upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000020FA0A7DC00>')),
                ('updated', models.DateTimeField()),
                ('real_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_state', to='account.profile')),
                ('watchlist', models.ManyToManyField(related_name='Profile_watch', to='account.profile')),
            ],
        ),
    ]
