# Generated by Django 4.1.2 on 2023-04-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_image'),
        ('property', '0004_alter_property_imaga1_alter_property_imaga2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='imaga1',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000025B2080DC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga2',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000025B2080DC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga3',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000025B2080DC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga4',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x0000025B2080DC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='watchlist',
            field=models.ManyToManyField(related_name='Profile_watch', to='account.profile'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_category', to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='property.category'),
        ),
    ]
