# Generated by Django 4.1.2 on 2023-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_image'),
        ('property', '0006_alter_category_property_alter_property_imaga1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='imaga1',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x000001F141BBDC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga2',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x000001F141BBDC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga3',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x000001F141BBDC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='imaga4',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='photo/<django.db.models.query_utils.DeferredAttribute object at 0x000001F141BBDC00>'),
        ),
        migrations.AlterField(
            model_name='property',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='Profile_watch', to='account.profile'),
        ),
    ]
