# Generated by Django 4.1.2 on 2023-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_imaga1_alter_property_imaga2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='property',
        ),
        migrations.AddField(
            model_name='category',
            name='property',
            field=models.ManyToManyField(blank=True, null=True, related_name='property_category', to='property.property'),
        ),
    ]
