# Generated by Django 4.1.2 on 2023-04-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_category_property_category_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='imaga1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imaga2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imaga3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='imaga4',
            new_name='image4',
        ),
    ]
